ktor {
    database {
        url = "jdbc:postgresql://localhost:5432/server_message"
        user = "mafen"
        password = ""
    }
    jwt{
        audience = "user-server"
        realm = "Access to 'hello'"
        domain = "http://localhost/"
        secret = "ajlkhf"
    }
}