ktor {
    database {
        url = "jdbc:postgresql://localhost:5432/server_message"
        user = "mafen"
        password = ""
    }
    jwt{
        audience = "user-server"
        realm = "Access to 'hello'"
        domain = "http://localhost/"
        secret = "x7K9mP2vL5nQ8wR3tY6uI0oA4sD7fG1hJ"
    }
}