ktor {
    database {
        driver = "org.postgresql.Driver"
        url = "jdbc:postgresql://localhost:5432/postgres"
        user = "postgres"
        password = "postgres"
    }
    jwt{
        audience = "user-server"
        realm = "Access to 'hello'"
        domain = "http://localhost/"
        secret = "ajlkhf"
    }
}